import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Poppins({ subsets: ["latin"], weight: ["300", "500", "700"] });

export const metadata = {
  title: "Next Crash Course",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {children} <Footer />
      </body>
    </html>
  );
}
